name: Deploy NodeJS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
# First we will see the application build or not , then we will deploy in EC2
  ssh_ec2:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: SSH into Symbiosis EC2 Instance
      env: 
        AWS_EC2_HOST_NAME: ${{ secrets.AWS_EC2_HOST_NAME  }}
        AWS_EC2_USER : ${{ secrets.AWS_EC2_USER  }}
        AWS_EC2_PRIVATE_KEY : ${{ secrets.AWS_EC2_PRIVATE_KEY  }}
      run: |
        curl ipinfo.io/ip
        echo "$AWS_EC2_PRIVATE_KEY" > private_key
        chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ${AWS_EC2_USER}@${AWS_EC2_HOST_NAME}
      
  deploy_nodejs:
    needs: ssh_ec2
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in EC2  
        run: |
            cd /app/govtech_devops_2022
            git checkout master
            git pull origin master
            touch hello.world 
